language: csharp
solution: CAS.NET.csproj

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update 
  - sudo apt-get install mono mono-xsp4 doxygen
  - # DEBUG:
  - mono --version
  - xsp4 --version
  - doxygen --version

script:
  - xbuild /p:Configuration=Debug CAS.NET.csproj
  - # Unit Tests:
  - nunit-console ./CAS.NET.Tests/bin/Debug/CAS.NET.Tests.dll
