language: csharp
solution: CAS.NET.csproj

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update 
  - sudo apt-get install mono-complete mono-xsp4 nunit-console doxygen
  - # DEBUG:
  - mono --version
  - xsp4 --version
  - doxygen --version

install:
  - nuget restore CAS.NET.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release CAS.NET.csproj
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./CAS.NET.Tests/bin/Release/CAS.NET.Tests.dll
