language: csharp
solution: CAS.NET.sln

install:
  - nuget restore CAS.NET.sln

script:
  - debconf-set-selections <<< 'mysql-server mysql-server/root_password password passwd'
  - debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password passwd'
  - apt-get -y install mysql-server
  - mysql -u root -p'passwd' -e "create database if not exists mydb"
  - xbuild /p:Configuration=Release CAS.NET.sln

notifications:
  email: false
