language: csharp
solution: CAS.NET.csproj

before_install:
  - # DEBUG:
  - mono --version
  - xsp4 --version
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update 
  - sudo apt-get install mono-complete mono-xsp4 nunit-console
  - # DEBUG:
  - mono --version
  - xsp4 --version

install:
  - nuget restore CAS.NET.sln

script:
  - xbuild /p:Configuration=Release CAS.NET.sln
  - #xbuild /p:Configuration=Release CAS.NET.csproj
  - #xbuild /p:Configuration=Release CAS.NET.Tests/CAS.NET.Tests.csproj
  - #nunit-console ./CAS.NET.Tests/bin/Release/CAS.NET.Tests.dll

notifications:
  email: false
