language: csharp
solution: CAS.NET.csproj

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update 
  - sudo apt-get install mono-complete mono-xsp4 nunit-console
  - # DEBUG:
  - mono --version
  - xsp4 --version

install:
  - nuget restore CAS.NET.sln

script:
  - xbuild /p:Configuration=Release CAS.NET.csproj
  - xbuild /p:Configuration=Release CAS.NET.Tests/CAS.NET.Tests.csproj
  - nunit-console ./CAS.NET.Tests/bin/Release/CAS.NET.Tests.dll

notifications:
  email: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "INZAfFJE00VmEpaIuvLFqfj5oq77Hq5f6Cw3H7HTM1uOxWMQPmNw6GbOIkJE27KaW9yBz1LRnzvFbhjDlNYrrP11DhS0ebIvKKy+PD3qNeemQCrNfrXSgz/4gBfnKAZvzaX7V7dwwn9HnkpLkV7biS1QWkaP5ZwtnjS7xxCDrUk="

addons:
  coverity_scan:
    project:
      name: "prozum/CAS.NET"
      description: "A computer algebra system written in ASP.NET"
    notification_email: nimoov@prozum.dk
    build_command_prepend: "xbuild /t:Clean"
    build_command:   "xbuild /p:Configuration=Release CAS.NET.csproj"
    branch_pattern: coverity
