language: csharp
solution: CAS.NET.sln

install:
  - nuget restore CAS.NET.sln

before_script:
  - mysql -e 'create database mydb;'

script:
  - xbuild /p:Configuration=Release CAS.NET.sln

notifications:
  email: false
