using System;
using Gtk;
using TaskGenLib;

namespace Gui.Tests
{
    class CASGui : Window
    {
        VBox oVB;
        VBox iVB;
        int globVarMin, globVarMax, globVarNum;
        string casfile;

        [STAThread]
        public static void Main(string[] args)
        {
            Application.Init();
            new CASGui();
            Application.Run();
        }

        public CASGui()
            : base("CAS.Net gui")
        {

            DeleteEvent += (o, a) => Application.Quit();

            globVarMax = 10;
            globVarMin = 1;
            globVarNum = 2;

            SetSizeRequest(300, 500);
            oVB = new VBox(false, 2);
            iVB = new VBox(false, 2);
            Table table1 = new Table(2, 2, false);
            ScrolledWindow scroll = new ScrolledWindow();

            Entry entry = new Entry();
            entry.HeightRequest = 20;
            entry.WidthRequest = 100;

            SetPosition(WindowPosition.Center);

            #region Menuer
            MenuBar mb = new MenuBar();
            Menu filemenu = new Menu();
            Menu addFileMenu = new Menu();


            MenuItem file = new MenuItem("MenuTest");
            file.Submenu = filemenu;

            MenuItem openFile = new MenuItem("Open File");
            openFile.Activated += (o, a) => OpenFile();

            MenuItem properties = new MenuItem("Properties");
            properties.Activated += (o, a) => OnActivatedProperties(globVarMin, globVarMax, globVarNum);

            MenuItem exit = new MenuItem("Exit");
            exit.Activated += OnActivated;



            MenuItem addItem = new MenuItem("Add Item");
            addItem.Submenu = addFileMenu;

            MenuItem gen = new MenuItem("Generate Assignment");
            gen.Activated += (o, a) => OnActivatedGen();

            MenuItem head = new MenuItem("Add headline");
            head.Activated += (object sender, EventArgs e) => AddHeadlineBox();

            MenuItem text = new MenuItem("Text Field");
            text.Activated += (object sender, EventArgs e) => AddTextBox();

            filemenu.Append(openFile);
            filemenu.Append(properties);
            filemenu.Append(exit);
            addFileMenu.Append(gen);
            addFileMenu.Append(head);
            addFileMenu.Append(text);
            mb.Append(file);
            mb.Append(addItem);
            #endregion Menuer

            table1.Attach(SetupLabAss(), 0, 1, 0, 1, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 3, 3); //Assignment
            table1.Attach(entry, 1, 2, 0, 1, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 3, 3); //answer
            table1.Attach(SetupTV(100, 100, ""), 0, 2, 1, 2, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 3, 3); // MR


            iVB.Add(table1);
            oVB.PackStart(mb, false, false, 8);
            oVB.Add(scroll);
            scroll.Add(iVB);

            Add(oVB);
            ShowAll();
        }

        // Menu to set number minimum, maximum and number of numbers used for autogenerated equations.
        void OnActivatedProperties(int min, int max, int num)
        {
            Window PropertiesWindow = new Window("This is a window");
            PropertiesWindow.SetDefaultSize(200, 200);

            VBox vbox = new VBox(false, 2);
            HBox hbox = new HBox(false, 2);

            string smin = min.ToString();
            string smax = max.ToString();
            string snum = num.ToString();

            Label varMin = new Label("VarMin");
            Label varMax = new Label("varMax");
            Label varNum = new Label("varNum");

            Table table = new Table(2, 4, false);

            table.Attach(varMin, 0, 1, 0, 1, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 5, 5);
            table.Attach(varMax, 0, 1, 1, 2, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 5, 5);
            table.Attach(varNum, 0, 1, 2, 3, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 5, 5);

            SpinButton sbMin = new SpinButton(0, 100000000, 1);
            sbMin.Value = globVarMin;
            sbMin.WidthRequest = 10;
            SpinButton sbMax = new SpinButton(0, 100000000, 1);
            sbMax.Value = globVarMax;
            sbMax.WidthRequest = 10;
            SpinButton sbNum = new SpinButton(2, 5, 1);
            sbNum.Value = globVarNum;
            sbNum.WidthRequest = 10;

            table.Attach(sbMin, 1, 2, 0, 1, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 5, 5);
            table.Attach(sbMax, 1, 2, 1, 2, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 5, 5);
            table.Attach(sbNum, 1, 2, 2, 3, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 5, 5);

            Button ok = new Button("Confirm");
            Button cancel = new Button("Cancel");

            cancel.Clicked += (object sender, EventArgs e) => PropertiesWindow.Destroy();

            ok.Clicked += delegate(object sender, EventArgs e)
            {
                globVarMin = sbMin.ValueAsInt;
                globVarMax = sbMax.ValueAsInt;
                globVarNum = sbNum.ValueAsInt;
                PropertiesWindow.Destroy();
            };

            hbox.Add(cancel);
            hbox.Add(ok);

            vbox.Add(table);
            vbox.Add(hbox);

            PropertiesWindow.Add(vbox);
            PropertiesWindow.ShowAll();
        }

        // Quits the application on call
        void OnActivated(object sender, EventArgs args)
        {
            Application.Quit();
        }

        // Generates new auto-generated equation
        void OnActivatedGen()
        {
            Table table = new Table(2, 2, false);
            Entry entry = new Entry();
            entry.HeightRequest = 20;
            entry.WidthRequest = 100;
            entry.Buffer.Text = "";

            table.Attach(SetupLabAss(), 0, 1, 0, 1, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 3, 3); //Assignment
            table.Attach(entry, 4, 5, 0, 1, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 3, 3); //answer
            table.Attach(SetupTV(100, 100, ""), 0, 5, 2, 3, Gtk.AttachOptions.Fill, Gtk.AttachOptions.Fill, 3, 3); // MR
            iVB.Add(table);
            ShowAll();

        }

        // Adds a oneline headline box
        void AddHeadlineBox()
        {
            Table table = new Table(1, 1, false);
            Entry entry = new Entry();

            entry.HeightRequest = 20;
            entry.WidthRequest = 100;
            entry.Buffer.Text = "";

            table.Attach(entry, 0, 1, 0, 1, AttachOptions.Fill, AttachOptions.Fill, 3, 3);
            iVB.Add(table);
            ShowAll();
        }

        // Adds a textbox
        // Please note that it currently writes all text on one line only.
        void AddTextBox()
        {
            Table table = new Table(1, 1, false);
            TextView textView = new TextView();

            textView.HeightRequest = 100;
            textView.WidthRequest = 200;
            textView.Visible = true;

            table.Attach(textView, 0, 1, 0, 1, AttachOptions.Fill, AttachOptions.Fill, 3, 3);
            iVB.Add(table);
            ShowAll();
        }

        // Generates the calculation for the equation
        public Label SetupLabAss()
        {
            Label labAss = new Label(TaskGen.MakeCalcTask(globVarMin, globVarMax, globVarNum));
            return labAss;
        }

        // Generates textbox
        public TextView SetupTV(int h, int w, string text)
        {
            TextView t = new TextView();
            t.HeightRequest = h;
            t.WidthRequest = w;
            t.Buffer.Text = text;
            t.Visible = true;
            return t;
        }

        void OpenFile()
        {
            OperatingSystem os = Environment.OSVersion;
            PlatformID pid = os.Platform;

            switch(pid)
            {
                case PlatformID.Win32S:
                case PlatformID.Win32Windows:
                case PlatformID.WinCE:
                case PlatformID.Win32NT: // <- if one, this is the one we really need
                {
                    System.IO.Stream myStream = null;
                    System.Windows.Forms.OpenFileDialog filechooser = new System.Windows.Forms.OpenFileDialog();

                    filechooser.InitialDirectory = "c:\\";
                    filechooser.Filter = "cas files (*.cas)|*.cas";
                    filechooser.FilterIndex = 2;
                    filechooser.RestoreDirectory = true;

                    if(filechooser.ShowDialog() == System.Windows.Forms.DialogResult.OK)
                    {
                        if ((myStream = filechooser.OpenFile()) != null)
                        {
                            using (myStream)
                            {
                                // Insert code to read the stream here.
                            }
                        }
                    }

                    break;
                }
                case PlatformID.Unix:
                case PlatformID.MacOSX:
                {
                    FileChooserDialog filechooser = new FileChooserDialog("Open file...", this, FileChooserAction.Open, "Cancel", ResponseType.Cancel, "Open", ResponseType.Accept);

                    filechooser.AddButton(Stock.Cancel, ResponseType.Cancel);
                    filechooser.AddButton(Stock.Open, ResponseType.Ok);

                    filechooser.Filter = new FileFilter();
                    filechooser.Filter.AddPattern("*.cas");

                    if (filechooser.Run() == (int)ResponseType.Accept)
                    {
                        casfile = filechooser.Filename;
                    }

                    filechooser.Destroy();

                    break;
                }
                default:
                {
                    break;
                }
            }
        }
    }
}